add authorization,registration
42musaev/bobcat_lms pull request #5
Opened 2020-09-21 15:28 UTC by 42chameleon

2020-09-21 20:08 UTC, ghostforpy commented
Аутентификация по токену не работает, необходимо дописывать настройки в settings.py

2020-09-21 20:11 UTC, ghostforpy reviewed
необходимо дописать настройки по DEFAULT_AUTHENTICATION_CLASSES в settings.py

2020-09-21 20:11 UTC, ghostforpy requested changes
необходимо дописать настройки по DEFAULT_AUTHENTICATION_CLASSES в settings.py

2020-09-22 08:41 UTC, 42musaev approved these changes

2020-09-22 08:42 UTC, 42musaev approved these changes

2020-09-22 08:44 UTC, 42musaev approved these changes

2020-09-22 08:52 UTC, ghostforpy approved these changes

2020-09-22 08:55 UTC, merged